# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(931, 690)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_make = QtWidgets.QPushButton(self.centralwidget)
        self.btn_make.setGeometry(QtCore.QRect(490, 190, 201, 51))
        self.btn_make.setStyleSheet("color: rgb(255, 170, 255);")
        self.btn_make.setObjectName("btn_make")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 20, 451, 631))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(490, 0, 241, 51))
        self.label.setStyleSheet("color: rgb(255, 255, 0);")
        self.label.setObjectName("label")
        self.list1 = QtWidgets.QListWidget(self.centralwidget)
        self.list1.setGeometry(QtCore.QRect(490, 40, 421, 131))
        self.list1.setObjectName("list1")
        self.bt_delete = QtWidgets.QPushButton(self.centralwidget)
        self.bt_delete.setGeometry(QtCore.QRect(700, 190, 211, 51))
        self.bt_delete.setStyleSheet("color: rgb(255, 170, 255);")
        self.bt_delete.setObjectName("bt_delete")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(490, 250, 421, 51))
        self.btn_save.setStyleSheet("color: rgb(85, 170, 255);")
        self.btn_save.setObjectName("btn_save")
        self.list2 = QtWidgets.QListWidget(self.centralwidget)
        self.list2.setGeometry(QtCore.QRect(490, 330, 421, 141))
        self.list2.setObjectName("list2")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(490, 490, 201, 51))
        self.btn_add.setStyleSheet("color: rgb(255, 170, 255);")
        self.btn_add.setObjectName("btn_add")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(490, 290, 241, 51))
        self.label_2.setStyleSheet("color: rgb(255, 255, 0);")
        self.label_2.setObjectName("label_2")
        self.btn_detach1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_detach1.setGeometry(QtCore.QRect(490, 600, 421, 51))
        self.btn_detach1.setStyleSheet("color: rgb(85, 170, 255);")
        self.btn_detach1.setObjectName("btn_detach1")
        self.btn_detach = QtWidgets.QPushButton(self.centralwidget)
        self.btn_detach.setGeometry(QtCore.QRect(700, 490, 211, 51))
        self.btn_detach.setStyleSheet("color: rgb(255, 170, 255);")
        self.btn_detach.setObjectName("btn_detach")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(490, 550, 421, 41))
        self.lineEdit.setStyleSheet("color: rgb(255, 85, 127);")
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 931, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_make.setText(_translate("MainWindow", "Створити замітку"))
        self.label.setText(_translate("MainWindow", "Список заміток"))
        self.bt_delete.setText(_translate("MainWindow", "Видалити замітку"))
        self.btn_save.setText(_translate("MainWindow", "Зберегти замітку"))
        self.btn_add.setText(_translate("MainWindow", "Додати до замітки"))
        self.label_2.setText(_translate("MainWindow", "Список тегів"))
        self.btn_detach1.setText(_translate("MainWindow", "Шукати замітки по тегу"))
        self.btn_detach.setText(_translate("MainWindow", "Відкріпити від замітку"))
        self.lineEdit.setText(_translate("MainWindow", "Введіть тег"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
